name: Node.js CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build . -t rjshk013/node-hellow:latest
        docker image list

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Docker Login
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push Image to Docker Hub
      run: docker push rjshk013/node-hellow:latest
